apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: eks-alerts
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: kubernetes-system-alerts
      rules:
        - alert: KubernetesNodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Node {{ $labels.node }} is not ready"
            description: "Node {{ $labels.node }} has been unready for more than 10 minutes."

        - alert: KubernetesPodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is restarting repeatedly."

        - alert: KubernetesNodeDiskPressure
          expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Node {{ $labels.node }} is under disk pressure"
            description: "Node {{ $labels.node }} is reporting disk pressure for more than 5 minutes."

        - alert: KubernetesNodeMemoryPressure
          expr: kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Node {{ $labels.node }} is under memory pressure"
            description: "Node {{ $labels.node }} is reporting memory pressure for more than 5 minutes."

    - name: eks-resource-alerts
      rules:
        - alert: KubernetesPodHighCpuUsage
          expr: sum(rate(container_cpu_usage_seconds_total{container!="POD", container!=""}[5m])) by (namespace, pod) / sum(kube_pod_container_resource_limits_cpu_cores) by (namespace, pod) > 0.85
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has high CPU usage"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is using more than 85% of its CPU limit for more than 10 minutes."

        - alert: KubernetesPodHighMemoryUsage
          expr: sum(container_memory_usage_bytes{container!="POD", container!=""}) by (namespace, pod) / sum(kube_pod_container_resource_limits_memory_bytes) by (namespace, pod) > 0.85
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has high memory usage"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is using more than 85% of its memory limit for more than 10 minutes."
