name: Terraform Validation

# Ensure only one workflow runs at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '*.tf'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: "1.10.0"

jobs:
  terraform-validation:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    outputs:
      should_release: ${{ steps.check-changes.outputs.terraform }}
      fmt_status: ${{ steps.fmt.outputs.status }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact --recursive
        continue-on-error: true

      - name: Check for Terraform changes
        uses: dorny/paths-filter@v3
        id: check-changes
        with:
          base: 'main'
          filters: |
            terraform:
              - '*.tf'

      - name: Set release output
        id: set-release
        if: steps.check-changes.outputs.terraform == 'true'
        run: echo "should_release=true" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}
          audience: sts.amazonaws.com
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Check Format
        id: fmt
        run: |
          if terraform fmt -check -recursive; then
            echo "status=clean" >> $GITHUB_OUTPUT
          else
            echo "status=needs-formatting" >> $GITHUB_OUTPUT
          fi

      - name: Find and validate Terraform directories
        run: |
          for dir in examples/*/; do
            if [ -n "$(find "${dir}" -name '*.tf' -print -quit)" ]; then
              echo "Processing ${dir}"
              cd "${dir}"
              terraform init
              terraform validate
              terraform plan -no-color
              cd - > /dev/null
            else
              echo "Skipping ${dir} - no Terraform files found"
            fi
          done

  trigger-release:
    needs: terraform-validation
    if: ${{ needs.terraform-validation.outputs.should_release }}
    uses: ./.github/workflows/release.yml
    with:
      fmt_status: ${{ needs.terraform-validation.outputs.fmt_status }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
